export default {
  SELECT_LEVEL: 'SELECT_LEVEL',
  REMEMBER_TIME_TICK: 'REMEMBER_TIME_TICK',
  RECALL_TIME_TICK: 'RECALL_TIME_TICK',
  NEXT_GAME: 'NEXT_GAME',
  REMEMBER_TIME_FINISHED: 'REMEMBER_TIME_FINISHED',
  RECALL_TIME_FINISHED: 'RECALL_TIME_FINISHED',
  SHAPE_MOVE: 'SHAPE_MOVE',
  SHAPE_ROTATE: 'SHAPE_ROTATE'
};
