import colors from '../style/colorPalette';

export default [
  { location: [0,0],
    points: [[0,2], [1,2], [1,1], [2,1]],
    color: colors.yellow,
    center: [2,2],
    angle: 0,
  },
  { location: [5,5],
    points: [[0,0], [0,1], [0,2], [0,3]],
    color: colors.grassGreen,
    center: [1,2],
    angle: 0,
  },
  { location: [3,3],
    points: [[0,0], [0,1], [1,0], [1,1]],
    color: colors.lightBlue,
    center: [1,1],
    angle: 0,
  },
  { location: [7,7],
    points: [[0,0], [0,1], [0,2], [1,2]],
    color: colors.green,
    center: [1,1],
    angle: 0,
  },
  { location: [0,0],
    points: [[1,1], [1,2], [0,2], [2,2]],
    color: colors.orange,
    center: [1,1],
    angle: 0,
  },
  { location: [7,7],
    points: [[1,0], [1,1], [1,2], [1,0]],
    color: colors.violet,
    center: [1,1],
    angle: 0,
  }
];
